[tool.poetry]
name = "turkish-validator"
version = "0.1.0"
description = ""
authors = ["Hasan Ã–zdemir <hasanozdemir1@trakya.edu.tr>"]
readme = "README.md"
packages = [{include = "turkish_validator"}]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.2.1"
black = "^23.1.0"


[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
